name: Analyse SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v3
      - name : virtual environnement
        uses : syphar/restore-virtualenv@v1
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install tox and any other packages
        run: pip install tox
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tox
        run: tox -e py
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
