name: Analyse SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Run commands
        run: |
          python3.11 -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip show Flask
          python -m unittest jwt_test.py
        
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            sonar.c.file.suffixes=-
            sonar.cpp.file.suffixes=-
            sonar.objc.file.suffixes=-
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
