name: Analyse SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run commands
        run: |
          pip install --upgrade pip
          python3.8 -m venv env
          source env/bin/activate
          pip install tox
          source env/bin/activate
          pip install -r requirements.txt
          pip show Flask
          source env/bin/activate
          tox -e py
        
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
